### ISSUE TITLE
considerations with infraspecies under synonyms, and 'authors' of autonyms

### ISSUE THREAD

**Issue by sagesteppe** [barnabywalker/kewr#60]
Hi, 

I just want to point out two areas which may be unintuitive to some users. They both reflect the children and parents of records.

We can use some material from the Ivesoid clade of the genus Potentilla  as an example

```{r}
library(kewr)

condition_1 <- search_powo("Ivesia lycopodioides")
condition_2 <- search_powo("Ivesia lycopodioides var. lycopodioides")

cond1_res <- condition_1[['results']]
cond1_res[unlist(lapply(cond1_res, `[`, 'accepted')) == T]
```

condition_1 as expected the accepted binomial (Potentilla lycopodioides) is returned

condition_2 Neither the accepted name of the species (P. lycopodioides) is returned, nor the accepted name of the variety (P.  l. var. lycopodioides)

Is it perhaps possible, or desirable, to match synonyms at the species level? And make note of accepted infraspecies?

```{r}
condition_3 <- search_powo("Potentilla lycopodioides var. megalopetala")
condition_4 <- search_powo("Potentilla lycopodioides var. lycopodioides")

condition_3[['results']][[1]]
condition_4[['results']][[1]]
```
What to do with authors of autonyms?

condition_3  as expected we retrieve this taxon and the author name
condition_4 as expected (but not intuitively) we retrieve the taxon, without the author name which is appended to *P. lycopodioides* 

I understand the reasons for not changing either of these functions, but feel modifications could be useful for folks. While it is sensible to not return the author of an autonym, the user than just has to run two queries to obtain the information (which I feel people will need for most applications). 

anyways just some food for thought

EDIT 
similar behavior is oberved with 'match_knms'

**Comment by barnabywalker** [comment]
Thank you for using `kewr` and suggesting some improvements.

These are all quite useful points but unfortunately it's not within the power of `kewr` to meet any of them. As a package, `kewr` is just an R wrapper around API endpoints for some of Kew's data products. The changes you describe would need to be made to Plants of the World Online instead of `kewr`.

You can see the behaviour you describe if you visit the POWO website, for instance searching for *Ivesia lycopodioides* returns results for the synonym *Ivesia lycopodioides* and the accepted name *Potentilla lycopodioides*. Searching for the now synonymised *Ivedia lycopodioides var. lycopodioides* returns nothing because this variety is not in the taxonomic backbone of POWO. In general, I think the taxonomic backbone of POWO does not always capture all infraspecifics that well, but I might be wrong on that.

I'm sorry I can't implement your suggestion - it would make searching POWO easier.
